### ISSUE TITLE
🐛 Bug: Feature Request and Tooling Issue Templates use Bug Report Checklist

### ISSUE THREAD

**Issue by danvk** [JoshuaKGoldberg/create-typescript-app#1287]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/create-typescript-app/issues?q=is%3Aissue) and found none that matched my issue.

### Expected

I'd expect that the Feature Request and Tooling issue templates would include tailored checklists.

### Actual

They include the bug report checklist.

### Additional Info

It seems unlikely that restarting my IDE would result in my feature being implemented 😀 But pulling the latest `main` and searching for related issues is still reasonable.

**Comment by JoshuaKGoldberg** [comment]
Haha, thanks, that's a good point. I hadn't thought too deeply about them after making those checklist for repos where it makes more sense.
